Mantid: MeanShifter Class Reference
MeanShifter Class Reference
This is the MeanShifter class, which is utilizing the Mean-shift approach which is a non-parametric feature-space analysis technique, a so-called mode seeking algorithm.
#include <MeanShifter.h>
Public Types
enum Type { FILTERING_GPU, SEGMENTATION_GPU, FILTERING_CPU, PROC }
the different meanshifter techniques available
Public Member Functions
MeanShifter (void)
This is the MeanShifter constructor.
~MeanShifter (void)
This is the MeanShifter destructor.
void applyMeanShift (cv::Mat *image, enum Type type)
actually applies a meanshift filter technique on the passed image pointer with the technique indicated by type
double getAverageElapsedTime (enum Type type)
a benchmark function.
Private Member Functions
void applyMeanShiftFiltering_GPU (cv::Mat *image)
uses meanShiftFiltering on the GPU
void applyMeanShiftSegmentation_GPU (cv::Mat *image)
uses meanShiftSegmentation on the GPU
void pyrMeanShiftFiltering_CPU (cv::Mat *image)
uses pyrMeanShiftFilterin on the CPU
void applyMeanShiftProc_GPU (cv::Mat *image)
creates a meanShift procedure only being applied to certain points
Private Attributes
std::vector< Timer > timers
vector holding the different timers to benchmark the different types of mean shifts
cv::gpu::GpuMat gpu_image_src
global gpu mats, which are necessary to compute gpu methods, since they need to be uploaded to the gpu
cv::gpu::GpuMat gpu_image_dst
Detailed Description
This is the MeanShifter class, which is utilizing the Mean-shift approach which is a non-parametric feature-space analysis technique, a so-called mode seeking algorithm.
It can be used to help tracking and finding objects in images and image sequences. A small introduction can be found here. http://docs.opencv.org/trunk/doc/py_tutorials/py_video/py_meanshift/py_meanshift.html
Definition at line 15 of file MeanShifter.h.
Member Function Documentation
void MeanShifter::applyMeanShift (cv::Mat * image, enum Type type)
actually applies a meanshift filter technique on the passed image pointer with the technique indicated by type
Parameters
image a pointer to the image, on which the meanshift is going to be applied on.
type the type of meanshifting which is going to be applied
Definition at line 14 of file MeanShifter.cpp.
References applyMeanShiftFiltering_GPU(), applyMeanShiftProc_GPU(), applyMeanShiftSegmentation_GPU(), pyrMeanShiftFiltering_CPU(), and timers.
void MeanShifter::applyMeanShiftFiltering_GPU (cv::Mat * image) private
uses meanShiftFiltering on the GPU
Parameters
image a pointer to the image, on which the meanshift is going to be applied on.
Definition at line 45 of file MeanShifter.cpp.
References gpu_image_src.
Referenced by applyMeanShift().
void MeanShifter::applyMeanShiftProc_GPU (cv::Mat * image) private
creates a meanShift procedure only being applied to certain points
Parameters
image a pointer to the image, on which the meanshift is going to be applied on.
Definition at line 66 of file MeanShifter.cpp.
Referenced by applyMeanShift().
void MeanShifter::applyMeanShiftSegmentation_GPU (cv::Mat * image) private
uses meanShiftSegmentation on the GPU
Parameters
image a pointer to the image, on which the meanshift is going to be applied on.
Definition at line 53 of file MeanShifter.cpp.
References gpu_image_src.
Referenced by applyMeanShift().
double MeanShifter::getAverageElapsedTime (enum Type type)
a benchmark function.
it returns the amount of milliseconds a technique took to compute. the type of which the benchmark is returned is indicated by the passed parameter
Parameters
type indicates the type of meanshift you want the elapsed time benchmark of
Returns
the time each processing of the meanshift took in average in milliseconds
Definition at line 71 of file MeanShifter.cpp.
References timers.
void MeanShifter::pyrMeanShiftFiltering_CPU (cv::Mat * image) private
uses pyrMeanShiftFilterin on the CPU
Parameters
image a pointer to the image, on which the meanshift is going to be applied on.
Definition at line 60 of file MeanShifter.cpp.
Referenced by applyMeanShift().
The documentation for this class was generated from the following files:
G:/DB/Dropbox/BA/code/BachelorThesis/BachelorThesis/MeanShifter.h
G:/DB/Dropbox/BA/code/BachelorThesis/BachelorThesis/MeanShifter.cpp